# Generated by Django 5.2.7 on 2025-10-30 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_customer_alter_booking_property"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEventLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="google", max_length=20)),
                ("ical_uid", models.CharField(max_length=255, unique=True)),
                ("calendar_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_link",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_id", models.CharField(max_length=255)),
                ("provider", models.CharField(default="google", max_length=20)),
                ("channel_id", models.CharField(max_length=255)),
                ("resource_id", models.CharField(max_length=255)),
                ("token", models.CharField(blank=True, max_length=255)),
                ("expiration", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="integrations.calendaraccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource_id"], name="integration_resourc_29794f_idx"
                    ),
                    models.Index(
                        fields=["channel_id"], name="integration_channel_f7134d_idx"
                    ),
                ],
                "unique_together": {
                    ("account", "calendar_id", "provider", "channel_id")
                },
            },
        ),
        migrations.CreateModel(
            name="CalendarSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_id", models.CharField(max_length=255)),
                ("provider", models.CharField(default="google", max_length=20)),
                ("sync_token", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_states",
                        to="integrations.calendaraccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "calendar_id", "provider")},
            },
        ),
    ]
