# Generated by Django 5.2.7 on 2025-10-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_customer_alter_booking_property"),
        ("customers", "0001_initial"),
        ("properties", "0002_property_calendar_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["property", "check_in", "check_out"], name="booking_prop_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="booking_status_idx"),
        ),
    ]
