# Generated by Django 4.2.7 on 2025-11-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asr", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(
                fields=["user", "-created_at"], name="trans_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transcription",
            index=models.Index(fields=["language"], name="trans_lang_idx"),
        ),
    ]
