# Generated by Django 5.2.7 on 2025-10-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="calendar_id",
            field=models.CharField(
                blank=True,
                help_text="External calendar id (e.g., Google)",
                max_length=255,
            ),
        ),
    ]
